### ISSUE TITLE
Better error checking for offline use.. Add in more reliability

### ISSUE THREAD

**Issue by willwade** [AceCentre/TranslateAndTTS#7]
- If you are offline are trying to translate - or its too slow or some other error - the error capturing right now isn't nice. We should try and do things to capture and quietly present errors
- Likewise with Azure TTS
- We should have an option to turn on or off these easygui message boxes. SOme people who have disabilities wont be able to close them (or alternatively, a way of it autoclosing the dialog after a set time
- In general I think the code could do with some refactoring to look nicer. It started off as a script but its getting quite hard to read now

**Comment by acerjay** [comment]
> * If you are offline are trying to translate - or its too slow or some other error - the error capturing right now isn't nice. We should try and do things to capture and quietly present errors
>     * We should have an option to turn on or off these easygui message boxes. SOme people who have disabilities wont be able to close them (or alternatively, a way of it autoclosing the dialog after a set time

https://github.com/AceCentre/TranslateAndTTS/commit/bb4c19a339634e64b6068f060ecf14361b2daaad

 Replace easygui with pyside6 | Messagebox has auto close feature (Default is 10 seconds) | Add Error handling when there is no existing settings.cfg and user click yes on launch the "Configure TranslateAndTTS" but discard the set-up. Normally, It will raise some error since no config file was found, but using this fix, a message box will notify the user that there is no config file created and the app will exit | Remove Pygame welcome message
